### ISSUE TITLE
android streaming

### ISSUE THREAD

**Issue by Igor755** [muxinc/examples#106]
the camera constantly flickers (in any state)

**Comment by GeneticGenesis** [comment]
Hi @Igor755, thanks for reporting this, we aren't able to reproduce this here. 

Please can you specify:
* What device you're using
* The version of Android you're running
* If you've made any modifications

And add a screen recording of what you're seeing.

This example is a thin wrapper around the [rtmp-rtsp-stream-client-java RTMP library](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java) so it may be that you'll need to raise an issue against that repository.

**Comment by Igor755** [comment]
Htc u ultra 
Android 8.0.0

**Comment by Igor755** [comment]
`

https://user-images.githubusercontent.com/25371495/131477966-b4047921-e662-493a-a4c8-23be3c40dc24.mp4

`

**Comment by Igor755** [comment]
i dont change code, just fork and try looking this. If needed i send issue in another rep

**Comment by GeneticGenesis** [comment]
Thanks @Igor755, can you try to recreate the issue using the example application in the https://github.com/pedroSG94/rtmp-rtsp-stream-client-java repository please, and let us know if you see the same results?

Thanks!

**Comment by Igor755** [comment]
ok, i create new issue. I try and get some problems with camera flick
