### ISSUE TITLE
Not working NetConnection.Connect.Closed

### ISSUE THREAD

**Issue by peterpaulis** [muxinc/examples#118]
Related https://github.com/shogo4405/HaishinKit.swift/discussions/1093

**Comment by philcluff** [comment]
Hi @peterpaulis, please could you give more details on which example isn't working, what you expect to see, and any logs you're seeing?

Thanks

**Comment by peterpaulis** [comment]
Hi i downloaded the example, updated the cocoapods

when entering a stream id like
aPPX7LAILQi2sPzIzINrwH56uiUFW00aDcfv2zV3xqqk

i get not connected errors

PS: i had the same experience when using the 'pure' Hasihin library

![IMG_CF3FBE29E757-1](https://user-images.githubusercontent.com/1956972/203563674-d0fcbec9-07c2-46c6-9c79-0006b5de1d53.jpeg)

**Comment by peterpaulis** [comment]
console output

using iOS16

```
Calling connect()
RTMP Status Handler called.
Calling publish()
2022-23-11 14:54:12.924 [Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:382] on(status:) > 
RTMP Status Handler called.
RTMP Connection was not successful.
Calling connect()
RTMP Status Handler called.
Calling publish()
2022-23-11 14:54:14.844 [Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:382] on(status:) > 
RTMP Status Handler called.
RTMP Connection was not successful.
Calling connect()
RTMP Status Handler called.
Calling publish()
2022-23-11 14:54:18.331 [Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:382] on(status:) > 
RTMP Status Handler called.
RTMP Connection was not successful.
Calling connect()
RTMP Status Handler called.
Calling publish()
2022-23-11 14:54:20.234 [Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:382] on(status:) > 
RTMP Status Handler called.
RTMP Connection was not successful.
```

**Comment by peterpaulis** [comment]
Omg facepalm on this... thanks so much

**Comment by philcluff** [comment]
No worries, glad you got it working!
