### ISSUE TITLE
[UIView bounds] must be used from main thread only

### ISSUE THREAD

**Issue by MchlG** [muxinc/examples#29]
Running the example project as well as my own implementation using LFLiveKit im getting this error in `GPUImageView.m` . 

`[UIView bounds] must be used from main thread only` on line 238 in this method `- (void)recalculateViewGeometry;`

I'm using LFLiveKit version 2.6 . I know this is an LFLiveKit issue but that project looks like it hasn't been touched in a few years so doubtful there will be any response.  

Im wondering if you've found a work around for this problem? I'm not very familiar with ObjC so im hesitant to try to fix this myself.

Would you consider re-working this example project and replacing LFLiveKit with [HaishinKit](https://github.com/shogo4405/HaishinKit.swift) ? I'm having trouble getting the HaishinKit project to work but it looks like a well maintained and living project and its written in Swift.

**Comment by GeneticGenesis** [comment]
Hey @MchlG,

Thanks for raising this. You're completely right that LFLiveKit is sadly abandonware at this point.

The good news is we're actively working on improving our story around RTMP ingest from iOS and Android at the moment, and we'll be updating this repository soon reflect those improvements.

I'd love to get your feedback on our plans here, feel free to drop me a mail if you want to talk in more depth: [my first name]@mux.com

Thanks!

**Comment by MchlG** [comment]
That's great news, looking forward to what y'all roll out! (LL-HLS support if announced at wwdc  😁). Thanks for the response!

**Comment by MchlG** [comment]
For whats it worth, i've found that this issue doesnt' occur I set the `AVAudioSession.Mode` to `.videoRecording`
