### ISSUE TITLE
Not using latest gradle dependencies.

### ISSUE THREAD

**Issue by faraz-ahmad** [muxinc/examples#31]
![Screenshot 2020-05-08 at 3 42 13 PM](https://user-images.githubusercontent.com/3992738/81396252-acba9700-9142-11ea-862b-3ed9a714d085.png)

**Comment by GeneticGenesis** [comment]
Hey @faraz-ahmad, just to let you know we've now replaced the Android example with something more modern, please let us know if you have any feedback or issues!

Thanks!
