### ISSUE TITLE
[ios-live-streaming] Live stream preview is not showing in full screen

### ISSUE THREAD

**Issue by gmakwana** [muxinc/examples#58]
I am trying to display preview view in full screen but it's not showing in full screen. Is there any way to display live stream in full screen?

**Comment by GeneticGenesis** [comment]
Hey @gmakwana, can you specify which example this is related to please, and maybe send a screenshot of what you're seeing?

Thanks!

**Comment by gmakwana** [comment]
![IMG_5281](https://user-images.githubusercontent.com/40565689/107246575-6211d680-6a56-11eb-8f9d-aeb4a400e8ae.PNG)

Here is the screenshot when I am trying to go live in full screen. It's showing black strip in top and bottom.

**Comment by GeneticGenesis** [comment]
Thanks, is this based on our example iOS application?

**Comment by gmakwana** [comment]
Yes it's based on iOS example. I have set constraint of preview view to full screen but it's still not showing live stream camera view in full screen.

**Comment by GeneticGenesis** [comment]
Thanks. 

As I understand it, this happens because the aspect ratio of the camera preview (16 : 9) is different to the aspect ratio of the screen itself, and so rather than stretching the preview, or cropping it, the camera preview is preferring to use black bars at the top / bottom.

What happens if you constrain the preview view to the top and bottom only, and add an aspect ratio constraint?

**Comment by gmakwana** [comment]
Is it a limitation of new version of code? It was working fine with old repo

Old repo: https://github.com/muxinc/example-ios-live-streaming

**Comment by GeneticGenesis** [comment]
The old example was based on [LFLiveKit](https://github.com/LaiFengiOS/LFLiveKit), which is out dated and is unmaintained.

The new version uses the maintained [HaishinKit](https://github.com/shogo4405/HaishinKit.swift) library. 

Did you try changing the constraints as I suggested?

**Comment by GeneticGenesis** [comment]
@gmakwana, I'm going to close this, please let me know if you are still having problems updating the constraints.

Thanks.
