### ISSUE TITLE
Want to change video codec to VP9

### ISSUE THREAD

**Issue by gmakwana** [muxinc/examples#65]
I want to change video codec to VP9 while streaming. I think current version of SDK is using h264 codec by default. How to change codec without changing pod file and what to do if we need to provide support to VP9?

**Comment by dylanjha** [comment]
Hi @gmakwana - which example project are you looking at?

**Comment by gmakwana** [comment]
I am looking at this example
https://github.com/muxinc/examples/tree/master/ios-live-streaming

**Comment by dylanjha** [comment]
Gotcha, on the capture side the video settings for Haishinkit looks like it gets set here: https://github.com/muxinc/examples/blob/fa879645056a8b64101258b7409f043d8f187159/ios-live-streaming/MuxLive/BroadcastViewController.swift#L87-L116

Are you looking to modify the codec on the capture side? Or are you looking to change what gets delivered on the live HLS stream? The delivery side is controlled by Mux and will be h264, regardless of which codec the original source uses.

**Comment by gmakwana** [comment]
We want to change codec from capture side while streaming. We want to set VP9 if possible.

**Comment by dylanjha** [comment]
The profile level gets set on this line:

```
.profileLevel: kVTProfileLevel_H264_Main_AutoLevel,
```

Which is according to the [HaishinKit settings docs](https://github.com/shogo4405/HaishinKit.swift#settings)

`kVTProfileLevel_H264_Main_AutoLevel` comes from Apple's [VideoToolbox](https://developer.apple.com/documentation/videotoolbox/kvtprofilelevel_h264_main_autolevel?language=objc)

It doesn't look like HaishinKit supports VP9 capture.

**Comment by GeneticGenesis** [comment]
Hi @gmakwana, 

This project uses the RTMP protocol via HaishinKit, and as such does not support sending VP9 over RTMP, as that's not one of the supported codecs in the RTMP protocol. 

Even if you did send VP9 over RTMP to Mux, we don't currently support that configuration for live streams.

Thanks.
