### ISSUE TITLE
Android Screen Cast

### ISSUE THREAD

**Issue by harisab2547** [muxinc/examples#84]
I can't Cast my screen with Camera Live stream in this app

**Comment by GeneticGenesis** [comment]
Hey @harisab2547, which example application are you struggling with please? 

Thanks!

**Comment by harisab2547** [comment]
I am using same project as a clone but in IOS screen can be cast with camera recording (Like Overlays) with this line of code
 
rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
 
 but in Android everything is handled with rtmpCamera object and we can't cast screen like we do in IOS.
 is there any Solution?

**Comment by GeneticGenesis** [comment]
Thanks @harisab2547,

The Android Example is based on rtmp-rtsp-stream-client-java, and only implements a subset of that library's capabilities, screen sharing isn't one of those.

It looks like there's an example of capturing the screen for streaming using rtmp-rtsp-stream-client-java here: 

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/displayexample

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/856

Let me know hoe you get on!

Thanks!
